# Generated by Django 2.1.7 on 2019-03-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='thdata',
        ),
    ]
